---
- name: Update Docker Compose containers
  hosts: all
  become: true
  tasks:
    - name: Change to directory containing docker-compose.yml
      ansible.builtin.command:
        cmd: "/home/jszopko/nginx-proxy-manager"
      args:
        chdir: /home/jszopko/nginx-proxy-manager
      become_user: root

    - name: Pull the latest images for Docker Compose services
      ansible.builtin.command:
        cmd: "docker-compose pull"
      args:
        chdir: /home/jszopko/nginx-proxy-manager
      become_user: root

    - name: Stop the running containers
      ansible.builtin.command:
        cmd: "docker-compose down"
      args:
        chdir: /home/jszopko/nginx-proxy-manager
      become_user: root

    - name: Start the updated containers
      ansible.builtin.command:
        cmd: "docker-compose up -d"
      args:
        chdir: /home/jszopko/nginx-proxy-manager
      become_user: root