---
- name: Update Docker Compose containers
  hosts: all
  become: true
  tasks:
    - name: Ensure correct permissions on the directory
      ansible.builtin.file:
        path: /home/jszopko/nginx-proxy-manager
      become_user: root

    - name: Change to directory containing docker-compose.yml
      ansible.builtin.shell: |
        cd /home/jszopko/nginx-proxy-manager
        docker compose pull
      become_user: root

    - name: Stop the running containers
      ansible.builtin.shell: |
        cd /home/jszopko/nginx-proxy-manager
        docker compose down
      become_user: root

    - name: Start the updated containers
      ansible.builtin.shell: |
        cd /home/jszopko/nginx-proxy-manager
        docker compose up -d
      become_user: root