---
- name: Cleanup Teleport installation
  hosts: all
  become: true
  tasks:

    - name: Stop any running Teleport processes
      ansible.builtin.shell: pkill -f teleport
      ignore_errors: yes

    - name: Remove Teleport data directory
      ansible.builtin.file:
        path: /var/lib/teleport
        state: absent

    - name: Remove Teleport configuration file
      ansible.builtin.file:
        path: /etc/teleport.yaml
        state: absent

    - name: Remove Teleport binaries
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /usr/local/bin/teleport
        - /usr/local/bin/tctl
        - /usr/local/bin/tsh