---
- name: Update Docker Compose App
  hosts: all
  become: true
  tasks:
    - name: Pull the latest images
      community.docker.docker_compose_v2:
        project_src: /home/jszopko/kuma/
        pull: always
      register: compose_pull
      become: true

    - name: Restart the Docker Compose application
      community.docker.docker_compose_v2:
        project_src: /home/jszopko/kuma/
        state: present
      when: compose_pull.changed
      become: true

    - name: Remove unused Docker images
      command: docker image prune -f
      become: true
